version: '3.2'
services:
  postgres_db:
    image: 'postgres:14.0'
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    restart: always

  backend:
    build: ./newsparser/.
    container_name: backend
    ports:
        - '8085:8085'
    depends_on:
        - postgres_db