version: '3.2'
services:
    db:
        image: 'postgres:14.0'
        environment:
            POSTGRES_DB: db
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
        restart: always